---
deployment:
      tasks:
        - export DEPLOYPATH=/home2/globalstweb/app.globalst.com.ve  # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        
